### ISSUE TITLE
pretrained models and logs 

### ISSUE THREAD

**Issue by dongzhang89** [lilujunai/Teacher-free-Distillation#1]
pretrained models and logs cannot be accessed？

**Comment by lliai** [comment]
Dear Professor Zhang, 
Thank you very much for your kind reminder!
The updated link is at https://pan.baidu.com/s/1F3QSX6MicA5qG5fxMOaCEg, pwd: tffd
In addition, thank you very much for your great ICCV21 work on self-KD in semantic segmentation. 
Our work performs a self-featured regular without assist classifier and also references your work in the paper.
Thank you again and we look forward to more discussions and cooperation in semantic segmentation!

Best wishes
Lujun Li

**Comment by dongzhang89** [comment]
@lilujunai  Great work. Thanks for your reply!
